### ISSUE TITLE
What can we do?

### ISSUE THREAD

**Issue by ntddk** [ntddk/obpro#1]
# 2048の拡張

実装案を募集しています．
## 例
- AIの実装
- [量子2048](http://uhyohyo.net/quantum2048/)
- [同位体256](http://jamesdonnelly.github.io/Isotopic256/)

**Comment by ntddk** [comment]
- パネルの移動をスプライトっぽい感じにする

**Comment by gucchan22** [comment]
僕は授業課題なのでそこまで凝る必要もないかなと思うので普通の2048でも良いと思います

**Comment by miyukki** [comment]
ベースから拡張していくのではなく、1から2048を作るってこと？

**Comment by ntddk** [comment]
現状の実装だとパネルの移動がカクカクなので，オフスクリーン用のクラスを実装するとかどうでしょうか

**Comment by miyukki** [comment]
みんなで？

**Comment by ntddk** [comment]
機能毎に振ったほうがいいかも．
- 滑らかなパネル移動
- アプレット化
- （リファクタリング）

等々．
何か案あれば書いていってください．

**Comment by ntddk** [comment]
アプレット未経験ですが，`JPanel`を`javax.swing.JApplet`に変更する程度で作れるのかしら．今時アプレットなんて流行らないけど

**Comment by ntddk** [comment]
概要の提出は @gucchan22 に任せていい？
自分はアプレット化をやろうと思います．

**Comment by gucchan22** [comment]
概要の提出OKです。

**Comment by ntddk** [comment]
@gucchan22 :+1:

**Comment by miyukki** [comment]
:+1:

**Comment by miyukki** [comment]
javax.swing.JAppletにするだけって楽すぎ

**Comment by ntddk** [comment]
他にinitとか変更しなきゃいけないっぽいですがよく知らない

**Comment by ntddk** [comment]
herokuでJava動かせるっぽいし後でdeployしてきますね

**Comment by gucchan22** [comment]
![2015-01-11 20 04 12](https://cloud.githubusercontent.com/assets/7811690/5695021/799562e6-99cd-11e4-828b-1120292c2395.png)

**Comment by miyukki** [comment]
AI+アップレット？

**Comment by ntddk** [comment]
誰かAI部分お願いします

**Comment by ntddk** [comment]
とりあえずアプレット化しましたが，ウィンドウサイズどうすればいいかな…
![ws000000](https://cloud.githubusercontent.com/assets/2392750/5695182/1788fb0c-99d8-11e4-8c7b-5c8cc8eaba89.JPG)

**Comment by miyukki** [comment]
アップレットってWebに埋め込むやつじゃないの？
AIはできないや

**Comment by ntddk** [comment]
AI廃止してリファクタリングお願いします．ウェブ埋め込みだけどウィンドウサイズ指定しなきゃいけないっぽいので．

**Comment by miyukki** [comment]
オープンソースのリファクタリングってもはや自分の趣向が入りそう

**Comment by ntddk** [comment]
@miyukki お好きなように

**Comment by gucchan22** [comment]
了解. これって2048のゲームプログラムって事です？

**Comment by ntddk** [comment]
@gucchan22 2048のゲームプログラムでないなら何なの…

**Comment by miyukki** [comment]
でもいちから作るわけじゃないということだよね

**Comment by ntddk** [comment]
取り敢えずアプレットとして動く2048があるので，
- @miyukki リファクタ
- @gucchan22 クラス構造+資料
- @shunkino シーケンス図

という作業配分でいいんですかね．他に手伝えることありますか？

**Comment by shunkino** [comment]
http://home2.dip.jp/stores/54b3929e6155cc72cc000026
pass:obpro

みたいな感じに作ってるんてすけど、だめだめだと思うのでアドバイスください。。。m(..)m

**Comment by ntddk** [comment]
@shunkino いい感じなんじゃないでしょうか．あと，画像はD&Dでここに貼れますよ．

**Comment by shunkino** [comment]
@ntddk
出先でAndroidで送信したので。。笑

**Comment by gucchan22** [comment]
たぶんこんなかんじ。間違ってたらおしえて

![2015-01-12 19 29 51](https://cloud.githubusercontent.com/assets/7811690/5701633/6a108d0e-9a91-11e4-9b6f-aa84b66f8517.png)

**Comment by miyukki** [comment]
@gucchan22 TilesをTileにしといて、それでコミットしとく

**Comment by gucchan22** [comment]
りょーかい

**Comment by miyukki** [comment]
Gameの`ensureSize(l : List<Tiles>`とかもだ…

**Comment by gucchan22** [comment]
closeすまん。Tiles変更しときます

**Comment by gucchan22** [comment]
ほい、修正しといた 

![2015-01-12 19 36 40](https://cloud.githubusercontent.com/assets/7811690/5701694/60d7f2da-9a92-11e4-9c7a-4ae0c5759716.png)

**Comment by miyukki** [comment]
まともにこのコード見たけどこれ結構酷い(みにくい)

**Comment by gucchan22** [comment]
一応プレゼンできたんだけどこれで提出でもOKですか？

**Comment by miyukki** [comment]
`Tile`のvalueを`private`にしたからそこだけ？（あと変更ありそうだけど一応作品概要の発表だからひとまずそれでいいのかな

**Comment by gucchan22** [comment]
え、これでグルワおわりじゃないん？

**Comment by miyukki** [comment]
`value`が`private`になり、`getValue`と`setValue`が
https://github.com/ntddk/obpro/commit/c4e9f5fb3f01061179affafbbdc91c460409dfe5#diff-8c5487587a14570b158e835848420091R6

**Comment by miyukki** [comment]
発表したら終わりじゃない？

**Comment by gucchan22** [comment]
はいよ、じゃあUMLに変更加えますよ

**Comment by gucchan22** [comment]
じゃあ提出しますね

**Comment by miyukki** [comment]
:+1: これあと発表があるのでは

**Comment by ntddk** [comment]
すげー雑なissue管理だけど発表の担当者を決めたらcloseしましょうかね…

**Comment by ntddk** [comment]
@gucchan22 一応提出資料をこっちにpushしてもらえますか

**Comment by gucchan22** [comment]
了解

**Comment by ntddk** [comment]
別にissue立てても良いのですが，ここで．
@miyukki 変更後のコードが動かないんですが，そちらの環境では動きますか？

```
java.lang.Error: Unresolved compilation problems: 
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    The method getLine(int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    The method rotate(int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    The method rotate(int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    The method rotate(int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    The method rotate(int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    The method rotate(int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    The method rotate(int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    The method availableSpace() from the type game refers to the missing type Tile
    The method availableSpace() from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    The method availableSpace() from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    The method tilesAt(int, int) from the type game refers to the missing type Tile
    The method tilesAt(int, int) from the type game refers to the missing type Tile
    The method tilesAt(int, int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    The method tilesAt(int, int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    The method tilesAt(int, int) from the type game refers to the missing type Tile
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type
    Tile cannot be resolved to a type

    at game.game.<init>(game.java:25)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at sun.applet.AppletPanel.createApplet(Unknown Source)
    at sun.applet.AppletPanel.runLoader(Unknown Source)
    at sun.applet.AppletPanel.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

```

**Comment by miyukki** [comment]
@ntddk Tile.javaがプロジェクトに入ってないんじゃない？

**Comment by ntddk** [comment]
あっ，本当だ．`git pull`しただけで未確認でした(；´Д｀)

**Comment by ntddk** [comment]
取り敢えず閉じます
